# Generated by Django 3.0.2 on 2020-02-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_feedback_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='profile',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed', to='social.MyProfile'),
        ),
    ]
